export const suggestions = {
  googleMaps: {
    businessCategories: [
      'Dental clinic',
      'Dentist',
      'Orthodontist',
      'Roofing contractor',
      'Plumber',
      'Electrician',
      'HVAC contractor',
      'Real estate agency',
      'Law firm',
      'Personal injury attorney',
      'Restaurant',
      'Auto repair shop',
      'Med spa',
      'Chiropractor',
      'Gym',
      'Marketing agency',
      'Insurance agency',
      'Accounting firm',
    ],
    searchTemplates: [
      'dentist',
      'roofing contractor',
      'personal injury lawyer',
      'real estate agency',
      'med spa',
      'auto repair',
      'restaurant',
      'plumber',
    ],
    locations: [
      'Austin, TX',
      'Phoenix, AZ',
      'Miami, FL',
      'Dallas, TX',
      'Los Angeles, CA',
      'New York, NY',
      'Atlanta, GA',
      'Chicago, IL',
    ],
  },
  salesNavigator: {
    titles: [
      'CEO',
      'Founder',
      'Owner',
      'President',
      'Managing Director',
      'VP Sales',
      'VP Marketing',
      'Head of Growth',
      'Head of Sales',
      'Sales Director',
      'Marketing Director',
      'Business Development Manager',
      'Account Executive',
      'Sales Manager',
      'Revenue Operations',
      'Growth Lead',
      'Partnerships Manager',
      'Chief Revenue Officer',
      'Chief Operating Officer',
      'Chief Executive Officer',
      'General Manager',
      'Regional Manager',
      'Customer Success Manager',
      'Procurement Manager',
      'Supply Chain Manager',
      'Logistics Manager',
      'Finance Director',
      'Controller',
      'HR Director',
    ],
    industries: [
      'Software Development',
      'Financial Services',
      'Real Estate',
      'Marketing Services',
      'Hospital and Health Care',
      'Construction',
      'Legal Services',
      'Insurance',
      'Manufacturing',
      'Transportation / Trucking / Railroad',
      'Logistics and Supply Chain',
      'Professional Services',
      'Retail',
      'Food and Beverage',
      'Telecommunications',
      'Accounting',
      'Education',
      'Staffing and Recruiting',
      'Biotechnology',
      'Information Services',
      'Computer Hardware',
      'Consumer Services',
      'Government Administration',
      'Facilities Services',
      'Utilities',
      'Oil and Energy',
      'Wholesale',
      'Aviation and Aerospace',
      'Hospitality',
      'Consumer Goods',
    ],
    seniorities: [
      'Owner',
      'CXO',
      'VP',
      'Director',
      'Manager',
      'Senior',
      'Partner',
      'Entry',
      'Intern',
      'Principal',
      'Lead',
      'Chief',
    ],
    functions: [
      'Sales',
      'Marketing',
      'Operations',
      'Business Development',
      'Finance',
      'Engineering',
      'Product',
      'Human Resources',
      'Information Technology',
      'Customer Success',
      'Support',
      'Legal',
      'Purchasing',
      'Logistics',
      'Procurement',
      'Supply Chain',
      'Administration',
      'Strategy',
      'Project Management',
      'Partnerships',
    ],
    geographies: [
      'United States',
      'Canada',
      'United Kingdom',
      'Australia',
      'Germany',
      'France',
      'Netherlands',
      'Spain',
      'Italy',
      'Ireland',
      'Sweden',
      'Norway',
      'Denmark',
      'Finland',
      'Belgium',
      'Switzerland',
      'Austria',
      'Singapore',
      'United Arab Emirates',
      'Saudi Arabia',
      'South Africa',
      'India',
      'Pakistan',
      'Philippines',
      'Malaysia',
      'New Zealand',
      'Mexico',
      'Brazil',
      'Chile',
      'Colombia',
    ],
    companies: [
      'Current Company',
      'Past Company',
      'Public Company',
      'Private Company',
      'Startup',
      'Mid-Market',
      'Enterprise',
      'Family Owned',
      'Franchise',
      'Holding Company',
      'Subsidiary',
      'Vendor',
      'Supplier',
      'Agency',
      'Consultancy',
      'Manufacturer',
      'Distributor',
      'Retail Chain',
      'Logistics Provider',
      'Software Vendor',
    ],
    headcounts: [
      '1-10',
      '11-50',
      '51-200',
      '201-500',
      '501-1,000',
      '1,001-5,000',
      '5,001-10,000',
      '10,001+',
      '11-100',
      '101-500',
      '501-1,000',
      '1,001-5,000',
      '5,001-10,000',
      '10,001-50,000',
      '50,001-200,000',
      '200,001+',
    ],
  },
};
