// Curated filter suggestions for the run form.
//
// Sources: the operator's own Sales Navigator Industry + Function picks
// (high-ticket B2B verticals) blended with LinkedIn's 13-sector industry
// taxonomy and classic email-rich local-business queries.
//
// Every Google Maps entry is query-safe: no registry jargon, no parentheses,
// no duplicates, and every search term × company type × location combination
// reads like something a real person would type into Google Maps.

export const suggestions = {
  googleMaps: {
    // Top-30 search terms, arranged by lead-yield vertical. Built from the
    // operator's industry picks (construction, energy, defense, logistics,
    // finance, health) and mapped business-function queries (real estate,
    // marketing, consulting, engineering, security).
    // Search terms = the roles & functions inside a company (Sales Navigator
    // style). Each one is a clean standalone Maps query ("Sales Dallas TX",
    // "Engineering Houston TX") that surfaces businesses built around that
    // function — every result is a company worth pitching.
    searchTemplates: [
      'Office Manager',
      'Practice Manager',
      // Revenue & growth
      'Sales',
      'Business Development',
      'Marketing',
      'Advertising',
      'Public Relations',
      'Media & Communication',
      'Customer Service',
      // Money & admin
      'Accounting',
      'Finance',
      'Bookkeeping',
      'Payroll',
      'Controller',
      'Insurance',
      'Legal',
      'Administrative',
      'Human Resources',
      'Recruiting',
      'Training',
      // Build & deliver
      'Engineering',
      'Operations',
      'Product Management',
      'Project Management',
      'Purchasing',
      'Procurement',
      'Supply Chain',
      'Logistics',
      'Transportation',
      'Distribution',
      'Manufacturing',
      'Quality Control',
      'Maintenance',
      'Safety',
      'Military & Protective',
      'Construction Management',
      'Estimator',
      'Superintendent',
      'Foreman',
      // Design & tech
      'Information Technology',
      'Design',
      'Architecture',
      'Research',
      'Development',
      'Consulting',
      // The top floor
      'Executive',
      'Management',
      'Owner',
      'CEO',
      'President',
      'General Manager',
      'Real Estate',
    ],
    // Top-30 category nouns — clean Maps category phrasing, safe to combine
    // with any search term.
    // Business categories = the top thriving US industries. Each stands alone
    // as a Maps query ("Oil & Gas Houston TX", "Construction Dallas TX").
    businessCategories: [
      // Energy & heavy industry
      'Oil & Gas',
      'Mining',
      'Renewable Energy',
      'Solar Energy',
      'Utilities',
      // Aviation, aerospace & maritime
      'Aviation',
      'Aerospace & Defense',
      'Maritime & Shipping',
      // Construction & trades
      'Construction',
      'Commercial Construction',
      'Roofing',
      'Electrical Services',
      'Plumbing',
      'HVAC',
      'Excavation',
      'Landscaping',
      'Home Services',
      // Manufacturing & industrial
      'Manufacturing',
      'Machinery Manufacturing',
      'Industrial Equipment',
      'Steel Fabrication',
      'Automotive',
      // Transportation & logistics
      'Trucking',
      'Freight & Logistics',
      'Warehousing',
      'Moving Services',
      // Health & life sciences
      'Healthcare',
      'Dental Clinics',
      'Veterinary Services',
      'Auto Repair',
      'Landscaping & Lawn Care',
      'Real Estate Agencies',
      'Warehousing & Distribution',
      'Accounting Firms',
      'Medical Spas & Aesthetics',
      'Electrical Contractors',
      'Staffing & Recruiting',
      'Restaurants & Food Service',
      'Insurance Agencies',
      'Hospitals',
      'Home Health Care',
      'Dental',
      'Veterinary',
      'Pharmaceutical',
      'Biotechnology',
      'Medical Devices',
      // Technology
      'Technology',
      'Software',
      'Cybersecurity',
      'IT Services',
      'Telecommunications',
      // Finance & professional
      'Financial Services',
      'Insurance',
      'Accounting',
      'Legal Services',
      'Real Estate',
      'Property Management',
      // Consumer & hospitality
      'Retail',
      'Restaurants',
      'Food & Beverage',
      'Hospitality',
      'Agriculture',
    ],
    // Top-30 Maps-safe company-type qualifiers. Short keywords that read
    // naturally when appended to a search term (e.g. "law firm Partners").
    companyTypes: [
      'LLC',
      'Inc',
      'Corp',
      'Company',
      'Group',
      'Enterprises',
      'Holdings',
      'Services',
      'Solutions',
      'Contractors',
      'Specialists',
      'Professionals',
      'Agency',
      'Firm',
      'Associates',
      'Partners',
      'Franchise',
      'Family Owned',
      'Veteran Owned',
      'Woman Owned',
      'Licensed',
      'Certified',
      'Insured',
      'Bonded',
      'Commercial',
      'Industrial',
      'Wholesale',
      'Manufacturers',
      'Suppliers',
      'Distributors',
    ],
    // Top US business metros by commercial density plus Canada's major hubs
    // (NAMER focus) — 48 markets that carry real B2B volume on Maps.
    locations: [
      'New York, NY',
      'Los Angeles, CA',
      'Chicago, IL',
      'Houston, TX',
      'Dallas, TX',
      'Phoenix, AZ',
      'San Antonio, TX',
      'San Diego, CA',
      'San Francisco, CA',
      'San Jose, CA',
      'Austin, TX',
      'Miami, FL',
      'Tampa, FL',
      'Orlando, FL',
      'Jacksonville, FL',
      'Atlanta, GA',
      'Charlotte, NC',
      'Raleigh, NC',
      'Nashville, TN',
      'Memphis, TN',
      'Washington, DC',
      'Baltimore, MD',
      'Philadelphia, PA',
      'Boston, MA',
      'Pittsburgh, PA',
      'Detroit, MI',
      'Columbus, OH',
      'Cleveland, OH',
      'Cincinnati, OH',
      'Indianapolis, IN',
      'Milwaukee, WI',
      'Minneapolis, MN',
      'St. Louis, MO',
      'Kansas City, MO',
      'Denver, CO',
      'Salt Lake City, UT',
      'Las Vegas, NV',
      'Seattle, WA',
      'Portland, OR',
      'Sacramento, CA',
      'Tucson, AZ',
      'Oklahoma City, OK',
      'Louisville, KY',
      'New Orleans, LA',
      'Richmond, VA',
      'Toronto, ON',
      'Vancouver, BC',
      'Montreal, QC',
    ],
  },
  salesNavigator: {
    // Decision-maker titles: the full C-suite plus VP/Director/Manager level
    // for every business function the operator targets.
    titles: [
      // Ownership & C-suite
      'Owner',
      'Founder',
      'Co-Founder',
      'CEO',
      'President',
      'Managing Director',
      'Managing Partner',
      'CFO',
      'COO',
      'CMO',
      'CTO',
      'Chief Revenue Officer',
      'Chief Commercial Officer',
      'Chief Strategy Officer',
      'General Manager',
      'VP',
      // Sales & business development
      'VP Sales',
      'Head of Sales',
      'Sales Director',
      'Regional Sales Manager',
      'VP Business Development',
      'Director of Business Development',
      'Account Executive',
      // Marketing & communications
      'VP Marketing',
      'Marketing Director',
      'Head of Growth',
      'Communications Director',
      'Brand Manager',
      // Finance & accounting
      'VP Finance',
      'Finance Director',
      'Controller',
      'Accounting Manager',
      // Operations & supply chain
      'VP Operations',
      'Operations Director',
      'Operations Manager',
      'Supply Chain Director',
      'Logistics Manager',
      'Warehouse Manager',
      // Purchasing & procurement
      'Procurement Director',
      'Procurement Manager',
      'Purchasing Manager',
      // Product & engineering
      'VP Product',
      'Director of Product Management',
      'VP Engineering',
      'Engineering Manager',
      // Admin, HR & real estate
      'VP Human Resources',
      'HR Director',
      'Director of Real Estate',
      'Facilities Manager',
      'Office Manager',
      'Practice Manager',
    ],
    // The operator's industry picks first, extended across LinkedIn's
    // 13-sector taxonomy for full B2B coverage.
    industries: [
      // Operator picks (from Sales Navigator)
      'Construction',
      'Defense and Space Manufacturing',
      'Oil and Gas',
      'Aviation and Aerospace Component Manufacturing',
      'Mining',
      'Agriculture, Construction, and Mining Machinery Manufacturing',
      'Hospitals and Health Care',
      'Renewable Energy Power Generation',
      'Transportation, Logistics, Supply Chain and Storage',
      'Financial Services',
      'Furniture and Home Furnishings',
      'Home Health Care Services',
      'Retail',
      // Industrial & manufacturing
      'Manufacturing',
      'Machinery Manufacturing',
      'Industrial Automation',
      'Building Materials',
      'Chemical Manufacturing',
      'Automotive',
      'Food and Beverage Manufacturing',
      // Logistics & trade
      'Truck Transportation',
      'Warehousing and Storage',
      'Wholesale',
      // Energy & environment
      'Utilities',
      'Environmental Services',
      // Health
      'Medical Practices',
      'Mental Health Care',
      'Pharmaceutical Manufacturing',
      'Medical Equipment Manufacturing',
      // Real estate & facilities
      'Commercial Real Estate',
      'Real Estate',
      'Facilities Services',
      // Professional & financial services
      'Banking',
      'Insurance',
      'Venture Capital and Private Equity',
      'Accounting',
      'Legal Services',
      'Staffing and Recruiting',
      'Marketing Services',
      'Advertising Services',
      // Technology
      'IT Services and IT Consulting',
      'Software Development',
      'Telecommunications',
      // Public & other
      'Government Administration',
      'Security and Investigations',
      'Professional Training and Coaching',
      'Hospitality',
    ],
    seniorities: [
      'Owner',
      'CXO',
      'VP',
      'Director',
      'Manager',
      'Senior',
      'Partner',
      'Entry',
      'Intern',
      'Principal',
      'Lead',
      'Chief',
    ],
    // The operator's function picks, completed with LinkedIn's standard
    // function taxonomy.
    functions: [
      'Sales',
      'Accounting',
      'Administrative',
      'Business Development',
      'Real Estate',
      'Purchasing',
      'Product Management',
      'Operations',
      'Military and Protective Services',
      'Media and Communication',
      'Marketing',
      'Finance',
      'Consulting',
      'Education',
      'Engineering',
      'Community and Social Services',
      'Human Resources',
      'Information Technology',
      'Legal',
      'Research',
      'Design',
      'Customer Success',
      'Support',
      'Strategy',
      'Project Management',
      'Partnerships',
      'Supply Chain',
      'Logistics',
      'Procurement',
      'Quality Assurance',
    ],
    geographies: [
      'United States',
      'Canada',
      'United Kingdom',
      'Australia',
      'Germany',
      'France',
      'Netherlands',
      'Spain',
      'Italy',
      'Ireland',
      'Sweden',
      'Norway',
      'Denmark',
      'Finland',
      'Belgium',
      'Switzerland',
      'Austria',
      'Singapore',
      'United Arab Emirates',
      'Saudi Arabia',
      'South Africa',
      'India',
      'Pakistan',
      'Philippines',
      'Malaysia',
      'New Zealand',
      'Mexico',
      'Brazil',
      'Chile',
      'Colombia',
    ],
    companies: [
      'Current Company',
      'Past Company',
      'Public Company',
      'Private Company',
      'Startup',
      'Mid-Market',
      'Enterprise',
      'Family Owned',
      'Franchise',
      'Holding Company',
      'Subsidiary',
      'Vendor',
      'Supplier',
      'Agency',
      'Consultancy',
      'Manufacturer',
      'Distributor',
      'Retail Chain',
      'Logistics Provider',
      'Software Vendor',
    ],
    // Canonical Sales Navigator headcount bands — one entry per band, no
    // overlapping duplicates.
    headcounts: [
      '1-10',
      '11-50',
      '51-200',
      '201-500',
      '501-1,000',
      '1,001-5,000',
      '5,001-10,000',
      '10,001+',
    ],
    keywords: [
      'B2B',
      'SaaS',
      'enterprise software',
      'construction management',
      'renewable energy',
      'logistics technology',
      'financial planning',
      'commercial real estate',
      'industrial equipment',
      'supply chain optimization',
      'healthcare services',
      'defense technology',
      'procurement',
      'business consulting',
      'digital transformation',
    ],
  },
};
