export const suggestions = {
  googleMaps: {
    // Top-30 categories, arranged by lead-yield vertical. Every entry is a
    // clean Maps category noun — safe to combine with any search term.
    businessCategories: [
      // Home & property services
      'Roofing',
      'HVAC',
      'Plumbing',
      'Electrical',
      'Landscaping',
      'Pest Control',
      'Tree Services',
      'Concrete Work',
      'Painting',
      'Garage Doors',
      // Health & wellness
      'Dental Services',
      'Medical Spas',
      'Chiropractic',
      'Physical Therapy',
      'Veterinary Care',
      'Dermatology',
      'Optometry',
      // Construction & energy
      'Construction',
      'Home Building',
      'Remodeling',
      'Flooring',
      'Solar Energy',
      'Excavation',
      // Professional & commercial
      'Legal Services',
      'Accounting',
      'Insurance',
      'Real Estate',
      'Marketing Services',
      'Financial Services',
      'Logistics & Freight',
    ],
    // Top-30 search terms, arranged by lead-yield vertical. These are the
    // highest-converting Google Maps queries for email-rich local businesses.
    searchTemplates: [
      // Home & property services
      'roofing contractor',
      'hvac contractor',
      'plumbing company',
      'electrician',
      'landscaping company',
      'painting contractor',
      'pest control',
      'tree service',
      'concrete contractor',
      'garage door repair',
      // Health & wellness
      'dentist',
      'med spa',
      'chiropractic clinic',
      'physical therapy clinic',
      'dental implant clinic',
      'veterinary clinic',
      'optometrist',
      'dermatology clinic',
      // Construction & energy
      'general contractor',
      'home builder',
      'remodeling contractor',
      'flooring contractor',
      'fencing contractor',
      'solar installer',
      'excavation contractor',
      // Professional & commercial
      'law firm',
      'accounting firm',
      'insurance agency',
      'real estate agency',
      'digital marketing agency',
    ],
    // Top-30 Maps-safe company-type qualifiers. Registry-style names produce
    // junk queries, so every entry here is a short keyword that reads
    // naturally when appended to a search term (e.g. "dentist LLC").
    companyTypes: [
      'LLC',
      'Inc',
      'Corp',
      'Company',
      'Group',
      'Services',
      'Solutions',
      'Contractors',
      'Specialists',
      'Experts',
      'Professionals',
      'Agency',
      'Firm',
      'Studio',
      'Clinic',
      'Center',
      'Associates',
      'Partners',
      'Franchise',
      'Family Owned',
      'Licensed',
      'Certified',
      'Insured',
      'Commercial',
      'Industrial',
      'Residential',
      'Wholesale',
      'Manufacturers',
      'Suppliers',
      'Local',
    ],
    locations: [
      'Austin, TX',
      'Phoenix, AZ',
      'Miami, FL',
      'Dallas, TX',
      'Los Angeles, CA',
      'New York, NY',
      'Atlanta, GA',
      'Chicago, IL',
      'Houston, TX',
      'San Antonio, TX',
      'San Diego, CA',
      'San Jose, CA',
      'Jacksonville, FL',
      'Tampa, FL',
      'Orlando, FL',
      'Charlotte, NC',
      'Raleigh, NC',
      'Nashville, TN',
      'Denver, CO',
      'Las Vegas, NV',
      'Seattle, WA',
      'Portland, OR',
      'Boston, MA',
      'Philadelphia, PA',
      'Washington, DC',
      'Minneapolis, MN',
      'Detroit, MI',
      'Columbus, OH',
    ],
  },
  salesNavigator: {
    titles: [
      'CEO',
      'Founder',
      'Owner',
      'President',
      'Managing Director',
      'VP Sales',
      'VP Marketing',
      'Head of Growth',
      'Head of Sales',
      'Sales Director',
      'Marketing Director',
      'Business Development Manager',
      'Account Executive',
      'Sales Manager',
      'Revenue Operations',
      'Growth Lead',
      'Partnerships Manager',
      'Chief Revenue Officer',
      'Chief Operating Officer',
      'Chief Executive Officer',
      'General Manager',
      'Regional Manager',
      'Customer Success Manager',
      'Procurement Manager',
      'Supply Chain Manager',
      'Logistics Manager',
      'Finance Director',
      'Controller',
      'HR Director',
    ],
    industries: [
      'Software Development',
      'Financial Services',
      'Real Estate',
      'Marketing Services',
      'Hospital and Health Care',
      'Construction',
      'Legal Services',
      'Insurance',
      'Manufacturing',
      'Transportation / Trucking / Railroad',
      'Logistics and Supply Chain',
      'Professional Services',
      'Retail',
      'Food and Beverage',
      'Telecommunications',
      'Accounting',
      'Education',
      'Staffing and Recruiting',
      'Biotechnology',
      'Information Services',
      'Computer Hardware',
      'Consumer Services',
      'Government Administration',
      'Facilities Services',
      'Utilities',
      'Oil and Energy',
      'Wholesale',
      'Aviation and Aerospace',
      'Hospitality',
      'Consumer Goods',
    ],
    seniorities: [
      'Owner',
      'CXO',
      'VP',
      'Director',
      'Manager',
      'Senior',
      'Partner',
      'Entry',
      'Intern',
      'Principal',
      'Lead',
      'Chief',
    ],
    functions: [
      'Sales',
      'Marketing',
      'Operations',
      'Business Development',
      'Finance',
      'Engineering',
      'Product',
      'Human Resources',
      'Information Technology',
      'Customer Success',
      'Support',
      'Legal',
      'Purchasing',
      'Logistics',
      'Procurement',
      'Supply Chain',
      'Administration',
      'Strategy',
      'Project Management',
      'Partnerships',
    ],
    geographies: [
      'United States',
      'Canada',
      'United Kingdom',
      'Australia',
      'Germany',
      'France',
      'Netherlands',
      'Spain',
      'Italy',
      'Ireland',
      'Sweden',
      'Norway',
      'Denmark',
      'Finland',
      'Belgium',
      'Switzerland',
      'Austria',
      'Singapore',
      'United Arab Emirates',
      'Saudi Arabia',
      'South Africa',
      'India',
      'Pakistan',
      'Philippines',
      'Malaysia',
      'New Zealand',
      'Mexico',
      'Brazil',
      'Chile',
      'Colombia',
    ],
    companies: [
      'Current Company',
      'Past Company',
      'Public Company',
      'Private Company',
      'Startup',
      'Mid-Market',
      'Enterprise',
      'Family Owned',
      'Franchise',
      'Holding Company',
      'Subsidiary',
      'Vendor',
      'Supplier',
      'Agency',
      'Consultancy',
      'Manufacturer',
      'Distributor',
      'Retail Chain',
      'Logistics Provider',
      'Software Vendor',
    ],
    // Canonical Sales Navigator headcount bands — one entry per band, no
    // overlapping duplicates.
    headcounts: [
      '1-10',
      '11-50',
      '51-200',
      '201-500',
      '501-1,000',
      '1,001-5,000',
      '5,001-10,000',
      '10,001+',
    ],
  },
};
